#include <fstream>
#include <vector>
#include <string>
#include <boost/algorithm/string.hpp>
#include "../cudd-3.0.0/cplusplus/cuddObj.hh"
#include <stdio.h>
#include <stdlib.h>
#include <set>
#include <iostream>
